export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    JOIN: '/join',
    NOT_FOUND: '*',
    KIA: '/kia-tigers',
    DOOSAN: '/doosan-bears',
    LOTTE: '/lotte-giants',
    SAMSUNG: '/samsung-lions',
    SSG: '/ssg-landers',
    NC: '/nc-dinos',
    LG: '/lg-twins',
    KIWOOM: '/kiwoom-heroes',
    KT: '/kt-wiz',
    HANHWA: '/hanwha-eagles',
}